### ISSUE TITLE
Install Error on RedHat

### ISSUE THREAD

**Issue by myloginid** [wush978/FeatureHashing#116]
Hi,

Pls check the below install error. The dependencies of  Rcpp (≥ 0.11), Matrix, digest (≥ 0.6.8), magrittr (≥ 1.5) are all satisfied.

[mm@x01tbipapp3a R]$ sudo R CMD INSTALL FeatureHashing_0.9.1.1.tar.gz
* installing to library ‘/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library’
* installing *source* package ‘FeatureHashing’ ...
** package ‘FeatureHashing’ successfully unpacked and MD5 sums checked
** libs
g++ -std=c++0x -I/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/Rcpp/include" -I"/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/digest/include" -I"/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/BH/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=c++0x -I/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/Rcpp/include" -I"/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/digest/include" -I"/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/BH/include"   -fpic  -g -O2 -c as.cpp -o as.o
as.cpp: In function ‘void pair_sort(int*, double*, size_t)’:
as.cpp:26: error: expected primary-expression before ‘[’ token
as.cpp:26: error: expected primary-expression before ‘]’ token
as.cpp:26: error: expected primary-expression before ‘a’
as.cpp:26: error: expected primary-expression before ‘b’
make: *** [as.o] Error 1
ERROR: compilation failed for package ‘FeatureHashing’
* removing ‘/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/FeatureHashing’
[mm@x01tbipapp3a R]$

Thanks,
Manish

**Comment by wush978** [comment]
@myloginid 

I guess you need to update your gcc to build FeatureHashing. In my last experience, I cannot build it with gcc 4.6 on our Centos server. But it works with gcc 4.8.
